apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: machine-apiserver-certs
  namespace: default
  labels:
    api: clusterapi
    apiserver: "true"
data:
  tls.crt: ${clusterapi_ca_cert}
  tls.key: ${clusterapi_ca_key}
